[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13.1"
log = "0.4.17"
anyhow = "1.0.62"
bytemuck = { version = "1.12.1", features = [ "derive" ] }